AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: backend-sqldb-sbntg
      DBSubnetGroupDescription: backend database subnet group
      SubnetIds:
        Fn::ImportValue: private-subnets
      Tags:
        - Key: environment
          Value:
            Ref: Environment

  SecurityGroup:
    Type:
    Properties:
      VpcId:
        Ref: vpc-id
      GroupName: db-scrtg
      SecurityGroupIngress:
        FromPort: 5432
        ToPort: 5432
        IpProtocol: tcp
        SourceSecurityGroupName:
          Fn::ImportValue: security-group
      Tags:
        - Key: environment
          Value:
            Ref: Environment

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      MaxAllocatedStorage: 20
      DBInstanceClass: db.t4g.micro
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      AvailabilityZone: us-east-1c
      DBInstanceIdentifier:
      DBName:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - database
      DBSubnetGroupName:
      Engine: postgres
      EngineVersion: 17
      MasterUsername:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - Ref: Environment
                    - database-username-password-secret
            - ":SecretString:username}}"
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - Ref: Environment
                    - database-username-password-secret
            - ":SecretString:password}}"
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: true
      BackupRetentionPeriod: 7
      DeleteAutomatedBackups: false
      DeletionProtection: true
      DBSecurityGroups:
        - db-sg-group
      VPCSecurityGroups:
        - Fn::ImportValue: security-group-id
      Tags:
        - Key: environment
          Value:
            Ref: Environment

Outputs:
  DatabaseUrl:
    Value:
      Fn::GetAtt:
        - Database
        - "Endpoint.Address"
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - database-url

  DatabasePasswordSecretArn:
    Value:
      Fn::GetAtt:
        - Database
        - "MasterUserSecret.SecretArn"
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - database-secret-arn

  SecurityGroupId:
    Value:
      Ref: SecurityGroup
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - database-scg
