AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  S3BucketMedias:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - rolesejogos
            - medias
      Tags:
        - Key: environment
          Value:
            Ref: Environment

Outputs:
  S3BucketMediasName:
    Value:
      Ref: S3BucketMedias
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - s3-bucket-medias-name

  S3BucketMediasDomainName:
    Value:
      Fn::GetAtt:
        - S3BucketMedias
        - DomainName
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - s3-bucket-medias-domain-name
