AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  GoogleClientSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - google-client-secret
      Tags:
        - Key: environment
          Value:
            Ref: Environment

  DatabaseUsernamePassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - database-username-password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: environment
          Value:
            Ref: Environment

Outputs:
  DatabaseUsernamePasswordArn:
    Value:
      Ref: DatabaseUsernamePassword
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - database-username-password-secret
