AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  # =================================
  #
  #        Collection
  #
  # =================================

  ImportPersonalCollectionFromLudopediaQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - import-personal-collection-from-ludopedia
      Tags:
        - Key: environment
          Value:
            Ref: Environment

Outputs:
  ImportPersonalCollectionFromLudopediaQueueUrl:
    Value:
      Ref: ImportPersonalCollectionFromLudopediaQueue
    Export:
      Name:
        Fn::Join:
          - "-"
          - - Ref: Environment
            - collection-import-personal-collection-from-ludopedia-queue-id
